#!/bin/bash

function print_ca_addr
{
    printf ">> Print ... \n"
    echo "EPICS_CA_ADDR_LIST      : $EPICS_CA_ADDR_LIST"
    echo "EPICS_CA_AUTO_ADDR_LIST : $EPICS_CA_AUTO_ADDR_LIST"
}


function unset_ca_addr
{
    printf "\n>> Unset ... EPICS_CA_ADDR_LIST and EPICS_CA_AUTO_ADDR_LIST\n"
    unset EPICS_CA_ADDR_LIST
    unset EPICS_CA_AUTO_ADDR_LIST
}

function set_ca_addr
{
    printf "\n<< Set   ... EPICS_CA_ADDR_LIST and EPICS_CA_AUTO_ADDR_LIST \n";
    export EPICS_CA_ADDR_LIST="$1"
    export EPICS_CA_AUTO_ADDR_LIST="$2";
    print_ca_addr
}



_HOST_IP="$(ip -4 route get 8.8.8.8 | awk {'print $7'} | tr -d '\n')";

unset_ca_addr

set_ca_addr "$_HOST_IP" "YES"

